all: blockingread nonblockingread

blockingread: blockingread.c
	gcc blockingread.c -o blockingread

nonblockingread: nonblockingread.c
	gcc nonblockingread.c -o nonblockingread

clean:
	rm blockingread nonblockingread
